### ISSUE TITLE
Added "Restart" as an action to Restart gateway

### ISSUE THREAD

**Issue by Whomiga** [edgan/att-fiber-gateway-info#3]
I have created a version of main.go in my cloned GIT repository that has "restart" as an action forcing a restart of the gateway. 
Other operations are unchanged. 
You can have the file if you want it.

**Comment by edgan** [comment]
Sure, give me a copy of the file.

**Comment by Whomiga** [comment]
What is the easiest way to do that? These comments don't allow for that type of file to be sent :-/

**Comment by edgan** [comment]
I would use a paste site like pastebin. A more standard alternative would be to make a pull request.

https://pastebin.com/

**Comment by Whomiga** [comment]
I committed it, but got an error due to not being authorized on the repo

**Comment by edgan** [comment]
You can fork it, and then push to your forked repo. Then you make a pull request.

**Comment by Whomiga** [comment]
Been a long time since I did anything with git - took me a few minutes but it should be available now (And up to date with changes you made since I originally got it)
